export const CHANGE_START_CURRENCY = 'CHANGE_START_CURRENCY';
export const CHANGE_END_CURRENCY = 'CHANGE_END_CURRENCY';
export const REVERSE_CURRENCY_SELECTION = 'REVERSE_CURRENCY_SELECTION';
export const FETCH_CURRENCY_RATE_REQUEST = 'FETCH_CURRENCY_RATE_REQUEST';
export const FETCH_CURRENCY_RATE_SUCCESS = 'FETCH_CURRENCY_RATE_SUCCESS';
export const FETCH_CURRENCY_RATE_FAILURE = 'FETCH_CURRENCY_RATE_FAILURE';
