export const BASE_API_URL =
  'https://bank.gov.ua/NBUStatService/v1/statdirectory/exchange?json';
  
export const GET_CURRENCY_REDUCER = {
  FETCH_CURRENCY_RATE_FAILURE: 'FETCH_CURRENCY_RATE_FAILURE',
  FETCH_CURRENCY_RATE_SUCCESS: 'FETCH_CURRENCY_RATE_SUCCESS',
  FETCH_CURRENCY_RATE_REQUEST: 'FETCH_CURRENCY_RATE_REQUEST',
};
export const CURRENCY_SELECTION_REDUCER = {
  CHANGE_START_CURRENCY: 'CHANGE_START_CURRENCY',
  CHANGE_END_CURRENCY: 'CHANGE_END_CURRENCY',
  REVERSE_CURRENCY_SELECTION: 'REVERSE_CURRENCY_SELECTION',
};
